### ISSUE TITLE
Can we request components? or share them?

### ISSUE THREAD

**Issue by vitalijalbu** [MA-Ahmad/templatesKart#12]
Can we request components? or share them?
I would like to add more components to that colletions so people can use them.

**Comment by MA-Ahmad** [comment]
Hi @vitalijalbu 

Thank you for reaching out! I appreciate your interest in contributing to this project. I absolutely welcome community contributions, including new components. 🚀

If you have specific components in mind, you can create a new issue suggesting the addition of those components. Alternatively, feel free to submit a pull request with the new component(s) you'd like to contribute.
