### ISSUE TITLE
Few Things out of Date wont pass build

### ISSUE THREAD

**Issue by judahsullivan** [MA-Ahmad/templatesKart#9]
I utterly love this project , I have been using this resource for about year now , and noticed that few things have gone out of date would love help maintain if possible.

**Comment by MA-Ahmad** [comment]
Yes, absolutely!

**Comment by judahsullivan** [comment]
hope your day going well found this broken imagelink in the sidebar as i was running through the files and wasnt sure if you wanted to hardcode something there or is there specific image you may have had wanted to show for the representation 



![Screenshot 2023-09-28 124315](https://github.com/MA-Ahmad/templatesKart/assets/106212053/cb155acf-84e8-400d-b04c-5aeac9629bab)

**Comment by msbalacse** [comment]
test

**Comment by MA-Ahmad** [comment]
Thank you for pointing this out. I've updated the image link.
